- src/base/playback.js
- src/base/playback.test.js
- src/components/player.js
- src/playbacks/html5_video/html5_video.js
- src/playbacks/html5_video/html5_video.test.js
Fix an implementation issue with the `consent()` method which is asynchronous.
It add a callback argument to prevents the use of timeout or process next tick trick.
```javascript
player.consent(() => {
// do something next...
})
```
> feat: add callback argument to consent method

- src/base/ui_object.js
- src/playbacks/html5_video/html5_video.js
- src/playbacks/html5_video/html5_video.test.js
- src/utils/utils.js
- src/utils/utils.test.js
It now stack and create DOM (video) elements instead of Zepto collection.
It perform a better cleanup by removing all atributes (required when using recycleVideo playback option without core-plugins)
It also fix a minor issue by properly add or remove the `controls` attribute if you set playback controls option to "any value" or false. By default, it does not add attribute if playback `controls` option not set.
Note: the video element `controls` attribute is not a boolean, the native controls are displayed if the attribute is added (value is ignored) and native controls are hidden if the attribute is missing.
> feat(utils): enchance dom recycler

- README.md
- src/components/loader/loader.js
- src/components/loader/loader.test.js
This PR adds the possibility to change the external plugins/playbacks load precedence from `before default plugins/playbacks` to `after default plugins/playbacks` via the new options `loadExternalPluginsFirst` and `loadExternalPlaybacksFirst`. 
* Create new option `plugins.loadExternalPluginsFirst`;
* Create new option `plugins.loadExternalPlaybacksFirst`;
* Update `addExternalPlugins` method the order to `concat` external and default plugins according to the new options;
* Update `removeDups` method to remain the feature for overwriting default plugins with external plugins.
Change the `public/j/clappr-config.js` for this:
``` javascript
var playerElement = document.getElementById("player-wrapper");
class TestPlugin extends Clappr.CorePlugin {
get name() { return 'test_plugin' }
get …
```
> Feature - Configure loading precedence of plugins and playbacks via options

- src/components/core/public/style.scss
The main ideia is to maintain the definition used right now inside [data-control] but it should avoid to set it deeply in DOM tree when it is already the default value because it is causing some conflicts for children with simple CSS class precedence.
```
var playerElement = document.getElementById("player-wrapper");
class TestPlugin extends Clappr.UICorePlugin {
get name() { return 'test_plugin' }
get supportedVersion() { return { min: Clappr.version } }
get template() { return Clappr.template(`<div class="plugin-test-wrapper" data-plugin-test></div>`) }
get attributes() {
return {
'class': 'plugin-test',
'data-plugin-test': ''
}
}
render() {
let styleOption = { baseUrl: this.options.baseUrl, playerId: this.options.playerId }
let style = Clappr.Styler.getStyleFor('.plugin-test { display: …
```
> Refactor - keep the precedence smooth

- src/utils/utils.js
- src/utils/utils.test.js
This PR adds tests for existent code on `utils.js`.
- Improve existent tests cases descriptions;
- Create tests for `assign` module;
- Create tests for `formatTime` module;
- Create tests for `QueryString` module;
- Create tests for `isNumber` module;
- Create tests for `currentScriptUrl` module;
- Create tests for `getBrowserLanguage` module;
- Create tests for `now` module;
- Create tests for `canAutoPlayMedia` module;
- Add more tests for `Config` module;
- Add more tests for `DoubleEventHandler` module;
> Tests - Increase test coverage for existent Utils modules

- src/base/events/events.test.js
This PR adds tests for existent code on `events.js`.
- Add more tests for `triggerEvents` method;
- Add more tests for `once` method;
- Add more tests for `off` method;
- Add more tests for `trigger` method;
- Add more tests for `stopListening` method;
- Add more tests for `register` method;
- Add more tests for `listAvailableCustomEvents` method;
- Add more tests for `listenTo` method;
- Add more tests for `listenToOnce` method;
> Tests - Increase test coverage for Events existent code

- src/base/adaptive_playback/adaptive_playback.js
- src/base/adaptive_playback/adaptive_playback.test.js
This PR adds tests for existent code on `adaptive_playback.js`.
- Use path alias to import modules on `adaptive_playback.js`
- Create tests for `isAdaptive` getter;
- Create tests for `isAutoAdaptive` getter/setter;
- Create tests for `activeVideoQualityLevels` getter;
- Create tests for `videoQualityLevels` getter;
- Create tests for `availableAudioOptions` getter;
- Create tests for `audioOptions` getter;
- Create tests for `availableClosedCaptions` getter;
- Create tests for `closedCaptions` getter;
> Tests - Increase test coverage for AdaptivePlayback existent code

- src/base/base_object/base_object.js
- src/base/base_object/base_object.test.js
This PR adds tests for existent code on `base_object.js`.
- Use path alias to import modules on `base_object.js`
- Create tests for `options` getter;
- Update existent tests;
>  Tests - Increase test coverage for BaseObject existent code

- src/base/container_plugin/container_plugin.js
- src/base/container_plugin/container_plugin.test.js
This PR adds tests for existent code on `container_plugin.js`.
- Use path alias to import modules on `container_plugin.js`
- Create tests for `enable` method;
- Create tests for `ErrorMixin` assignment;
- Create tests for `extend` feature;
>  Tests - Increase test coverage for ContainerPlugin existent code

- src/base/core_plugin/core_plugin.js
- src/base/core_plugin/core_plugin.test.js
This PR adds tests for existent code on `core_plugin.js`.
- Use path alias to import modules on `core_plugin.js`
- Create tests for `enable` method;
- Create tests for `ErrorMixin` assignment;
- Create tests for `extend` feature;
- Create tests for `external interface` feature;
>  Tests - Increase test coverage for CorePlugin existent code

- src/base/error_mixin/error_mixin.js
- src/base/error_mixin/error_mixin.test.js
This PR adds tests for existent code on `error_mixin.js`.
- Use path alias to import modules on `error_mixin.js`
- Create tests for `createError` method;
>  Tests - Increase test coverage for ErrorMixin existent code

- README.md
- src/playbacks/html5_video/html5_video.js
- src/playbacks/html5_video/html5_video.test.js
This PR adds a minimum DVR support to HTML5Playback. With this PR, Clappr now supports play live streams with DVR on iOS devices. This new implementation adds the necessity to revisit all external playbacks to unify the DVR support and configuration but this refactor needs to be in another PR for priority purposes.
* Create new option `playback.minimumDvrSize`;
* Option to define the minimum DVR size to active seek on Clappr live mode.
* Create new internal reference `_minDvrSize`;
* Playback internal reference for the option `playback.minimumDvrSize`.
* If the option `minimumDvrSize` is not defined, the default value is **60 seconds**.
* Refactor `getDuration` method;
* Add new logic to get duration for live media.
* Create new getter `dvrEnabled`;
* This getter checks:
* If the playback …
> Feature - Add minimum DVR support to HTML5Video Playback

- src/components/loader/loader.js
- src/components/loader/loader.test.js
This PR adds tests for existent code on the `loader.js`. Also, fix one problem in the overwrite flow on the `registerPlayback` static method.
- Use path alias to import modules on `loader.js`/`loader.test.js` files;
- Fix overwrite feature on `registerPlayback` method;
- Improve existent tests messages;
- Update existent tests for `validateExternalPluginsType` method;
- Create tests for `checkVersionSupport` method;
- Create tests for `unregisterPlugin` method;
- Create tests for `unregisterPlayback` method;
>  Tests - Create tests for Loader existent code

- src/components/error/error.js
- src/components/error/error.test.js
This PR adds tests for existent code on `error.js`.
- Use path alias to import modules on `error.js`/`error.test.js` files;
- Add more readability to `constructor` declaration;
- Add more tests for `constructor`;
>  Tests - Create tests for PlayerError existent code

- src/components/core/core.js
- src/components/core/core.test.js
- src/utils/utils.js
At some browsers, the `requestFullscreen` method returns an error even when the fullscreen mode is activated successfully.
This PR adds a delay to check for reject response of `requestFullscreen` method if it's a promise and only prints the error if the fullscreen mode has not activated.
- `utils.js`:
- Returns the response of `requestFullscreen` method if is a promise;
- `core.js`:
- Handles the promise on browsers that support this response;
- Handles the `reject` delaying the response;
- Checks if the element is already in fullscreen mode before throws the error;
This problem only appears on the https://github.com/clappr/clappr or https://github.com/clappr/clappr-plugins projects. So, generate one build of `@clappr/core` and add inside those projects or use the `yarn link` approach to …
>  Core - Handle fullscreen unexpected behavior

- src/components/container_factory/container_factory.js
- src/components/container_factory/container_factory.test.js
This PR adds tests for existent code on `container_factory.js`. Also, refactor old code to use current JS features.
- Use path alias to import modules on `container_factory.js`/`container_factory.test.js` files;
- Add more readability to `createContainer` method;
- Use spread operator instead Zepto `extends`;
- Create tests for `createContainer` method;
- Create tests for `createContainers` method;
- Create tests for `addContainerPlugins` method;
> Tests - Create tests for ContainerFactory existent code

- src/components/container/container.js
- src/components/container/container.test.js
- src/playbacks/html5_video/html5_video.js
In some cases, the playback can trigger a `PLAYBACK_SEEK` event via `seeking` event from `html5`.
In this case, the container was not notifying the seek.
The `PLAYBACK_SEEK` in `html5` now notifies the event with the playback `current time` and, also, before calling `buffering` to keep the order of seek -> buffering events.
> Container - Propagate seek event from playback

- src/components/core_factory/core_factory.js
- src/components/core_factory/core_factory.test.js
This PR adds tests for existent code on `core_factory.js`. Also, one refactoring on the `constructor` code to remove unnecessary operation.
-  Use `src` path alias to import modules on `core_factory.js` file;
- Send `player.options` on `super()` call instead add options manually via `this_options` reference;
- Create tests for `constructor`;
- Create tests for `loader` getter
- Create tests for `create` method;
- Create tests for `addCorePlugins` method;
- Create tests for `setupExternalInterface` method;
> Tests - Create tests for CoreFactory existent code

- src/playbacks/html5_video/html5_video.js
A small regression has been introduced in Clappr core since version 0.4.8 preventing video to restart after it ended.
It is due to "synchonous" call of consent() method in poster plugin. (this was discuted [here](https://github.com/clappr/clappr-plugins/commit/e19b53fd2f75bde532d09673f0505b533daa6cb9#commitcomment-38321380))
To fix the issue, i used a simple custom flag on video element to avoid unnecessary additional call of load() method.
It should fixes Clappr player issues [1984](https://github.com/clappr/clappr/issues/1984) and [1982](https://github.com/clappr/clappr/issues/1982).
> fix: allow video to restart when ended

- src/base/playback/playback.js
- src/base/ui_object/ui_object.js
- src/components/container/container.js
- src/components/core/core.js
- src/components/player/player.js
- src/playbacks/html5_video/html5_video.js
- src/utils/utils.js
The `defaultOptions.playback` being overwritten when the received options on Clappr init have the `playback` options too. The expected behavior is the merge between those two options.
This PR applies the expected behavior using the Zepto `$.extend()` method with the option for a [deep merge approach](https://zeptojs.com/#$.extend).
* Applies the deep merge config on every `$.extend` call;
* Play one media;
* Print the value of `player.options.playback` on developr tools console tab;
* The object should contain the property `recycleVideo: true` and `controls: true`.
> Player - Fix initial options merge

- src/components/container/container.js
- src/components/container/container.test.js
This PR allows Containers actions such as `play`, `pause`, and `stop`, to receive parameters and bridge these parameters to the `Playback`.
The Container events related to these actions will send the parameters to anything who is listening to these `container events`.
- `src/components/container/container.js`: Allows `play`, `pause`, and `stop` methods to receive parameters and store them on `actionsMetadata` key. These parameters are sent when Container triggers related events.
- `src/components/container/container.test.js`: Create tests for Container extension. 
1. Run this PR project
2. On the Developer Tools, listen to Containers `play`, `pause`, or `stop`, and log his callback. Ex: `player.listenTo(player.core.activeContainer, Clappr.Events.CONTAINER_PAUSE, (...args) => …
> Extend container actions accepting parameters

- src/base/events/events.js
- src/base/playback/playback.js
- src/base/playback/playback.test.js
- src/components/container/container.js
- src/components/container/container.test.js
This PR introduces a new API to the playback interface to standardize the way audio tracks are queried and updated. As of now, Clappr does not provide a set of APIs on the playback to interact with the audio tracks in the stream (i.e., when the content is adaptive) nor does it provide events that other plugins can subscribe to when something happens to the audio tracks.
In order to address the aforementioned issues, 3 methods/properties were added to the playback interface and 2 events were defined:
* `get audioTracks`: returns a list of audio tracks available to be used by the playback;
* `get currentAudioTrack`: returns the audio track that is active at the moment;
* `switchAudioTrack(id)`: updates the current audio track to the one with the provided id.
* `PLAYBACK_AUDIO_AVAILABLE`: …
> Playback: add audio track public API and events

- src/components/core/core.js
This PR fixes two issues related to the use of full screen mode on Clappr in iOS.
Previously, Clappr's `core` method `isFullscreen` used `document` variables (e.g. `fullscreenElement`) to identify if the player was on full screen mode. This couldn't be verified, however, when using an iOS device, in which case, the `video` element's `webkitDisplayingFullscreen` variable must be checked.
Clappr's `core` method `toggleFullscreen` wasn't able to deactivate full screen mode programmatically in iOS devices. This happened because `cancelFullscreen` was never called with Clappr's `video` element when running the player in iOS, using the default `document` element.
- Clappr's `core` can now identify correctly if Clappr is on Full screen mode in iOS;
- Clappr's `core` can now cancel Full screen …
> Core - Fix integration with full screen controls in iOS

- .github/pull_request_template.md
This PR updates the repository's template for new Pull Requests.
- `.github/pull_request_template`: Updated pull request template
This PR doesn't affect Clappr. No tests required.
> GitHub – Update Pull Request Template

- src/components/player/player.js
Moves the logic that checks whether the parent element is an ID or an Object to a new method. Making the code inside the constructor more readable.
- `player.js`: change `setParentId` to `_getParentElement` method
> Refactor attach element on Player constructor

- README.md
Fixes issue #79. 
Same PR as i did before on #84, just reopened (due to hacktoberfest contribution).
> docs: fix broken URL for "all existing events"

- src/plugins/strings/strings.js
Just add Chinese language as shown above.
Only in file `/src/plugins/strings/strings.js`, which
from line 119 to 126 add these:
```
'zh': {
'live': '直播',
'back_to_live': '返回直播',
'disabled': '已禁用',
'playback_not_supported': '您的浏览器不支持该视频的播放。请尝试使用另一个浏览器。',
'default_error_title': '无法播放视频。',
'default_error_message': '在尝试加载视频时出现了问题。',
},
```
and line 140:
`this._messages['zh-CN'] = this._messages['zh']`
1. config the `language` to `zh-CN`.
2. you'll see the Chinese UI.
> Add Chinese language.

- README.md
- package.json
- src/components/core/core.js
- yarn.lock
This PR fixes tests for Core. https://github.com/clappr/clappr-core/issues/86
- It removes:
- Old Karma test fragments
- Travis CI badge from readme
- Update dependencies
Just run the tests normally.
> Fix core Tests

- src/components/player/player.js
This PR allows Clappr's callbacks such as `onPlay`, `onPause`, and `onStop` to receive parameters from the  `actionsMetadata` object sent through the Clappr's `Container` methods (`play`, `pause` and `stop`).
For more context, the `actionsMetadata` object was introduced in https://github.com/clappr/clappr-core/pull/73. 
- `player.js`: Allows the `onPlay`, `onPause`, and `onStop` callbacks to use parameters from Container actions' `actionsMetadata` object.
1. Run this branch with the following callbacks configured in the Player `options`:
```
events: {
onPlay: (eventMetadata) => { console.log(eventMetadata) },
onPause: (eventMetadata) => { console.log(eventMetadata) },
onStop: (currentTime, eventMetadata) => { console.log(eventMetadata) },
}
```
2. On your browser's Developer Tools …
> Callbacks – Add Event Parameters from Container Actions

- src/components/player/player.js
This PR fixes an issue introduced in https://github.com/clappr/clappr-core/pull/82 that allowed the attaching of an undefined element.
- `player.js`: Add conditional to attaching of `parentElement`
> Fix attach element on Player constructor

- src/components/browser/browser.js
This PR fixes the `isEdge` method from the `Browser` class. Its identification of Microsoft's current browser was deprecated.
For more information on this change, check [Microsoft's Edge documentation on User-Agent identification](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/user-agent-guidance).
1. Access each of the main browsers (Chrome, Edge, Firefox, Safari) and check if their respective methods are working (`isChrome`, `isEdge`, `isFirefox`, `isSafari`)
> Browser – Fix Microsoft Edge User Agent Identification

- src/components/browser/browser.js
This PR implements the new getters `isWindows`, `isMacOS` and `isLinux`, which identify the device's operational system.
1. Run Clappr.
1. Access your browser of choice and type the following in your DevTools:
```
console.log({
isWindows: Clappr.Browser.isWindows,
isMacOS: Clappr.Browser.isMacOS,
isLinux: Clappr.Browser.isLinux,
})
```
3. It should return correctly.
> Browser – Operational System Identifiers

- src/plugins/strings/strings.js
`This PR fixes a typo in unsupported playback message`
- `strings.js`:
- Fix the word "supporta" to "suporta"
1. Using a unsupported media check the message in portuguese
> fix: typo in playback not supported message

- src/playbacks/html5_video/html5_video.js
- src/playbacks/html5_video/html5_video.test.js
This PR implements two new options to customize playhead moving check: `disablePlayheadMovingCheck` and `playheadMovingCheckInterval`.
The first one is used to disable the playhead moving check, and the second allows to customize the interval time between checks.
The motivation for this change is that there are some scenarios where `500ms` is not enough to update the `currentTime` and some `PLAYBACK_BUFFERING` were being triggered not correctly.
- `html5_video.js`:
- Implement two new options: `disablePlayheadMovingCheck` and `playheadMovingCheckInterval`
- Prevent exceptions when checking `canPlay` with `undefined` value
> HTML5 Video - Allow customizing playhead moving check

- src/playbacks/html5_video/html5_video.js
This MR is a complement of the https://github.com/clappr/clappr-core/pull/109.
It just fixes the logic to disable the playhead moving check.
> HTML5 Video - Fix logic to disable playhead moving check

- src/base/playback/playback.js
This PR implements two new getters for Clappr's `Playback` class.
Currently, this getter has been implemented onto our two main playbacks: `HlsjsPlayback` and `DashShakaPlayback`. If possible, please check out the following MRs as well:
- https://github.com/clappr/hlsjs-playback/pull/43
- https://github.com/clappr/dash-shaka-playback/pull/126
> Playback – Add getters related to Latency information

- src/base/events/events.js
- src/base/playback/playback.js
- src/components/container/container.js
- src/playbacks/html5_video/html5_video.js
This PR implements the picture in picture feature that can be useful for PiP Plugins
- `html5_video.js`:
- add handlers to picture-in-picture 
- `events.js`: 
-  add events to handle EnterPIP and ExitPIP
- `container.js`: 
- bind pip playback events to container events
- `playback.js`: 
- add methods to pip mode
1. There's an example in code comments that uses a simple button
> Add Picture in Picture events in HTML5Video

- src/playbacks/html5_video/html5_video.js
This PR updates HTML5 Picture-In-Picture to handle binge-watching
- `html5_video.js`: removing exitPiP from destroy
> Handle PiP Binge-Watching in HTML5Video
